# Reference:
# https://github.com/nabilnalakath/flutter-githubaction/blob/master/.github/workflows/main.yml
# https://ithelp.ithome.com.tw/articles/10262682
# https://pjchender.dev/devops/devops-github-action/
on: push
name: Test, Build And Release
jobs:
  test:
    name: Test Unit, Widget, integration_test
    runs-on: ubuntu-latest
    steps:
      # Checkout Code from github
      - name: Checkout code
        uses: actions/checkout@v4

      # install java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '20'

      # install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
      
      # Run Test
      - name: Run `flutter test`
        uses: flutter test
  # build:
    # steps:
  # release:
    # steps:
